'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const M=require('../engine/math'),G=require('../engine/game-theory'),B=require('../engine/boss'),F=require('../engine/fair-division'),P=require('../js/power-index'),VM=require('../js/emulation-engine');
const root=path.resolve(__dirname,'..');const dest=process.argv[2]||path.join(root,'audit');fs.mkdirSync(dest,{recursive:true});
const model={schema:'hail-backward-audit/v1',source:'Uploaded 0.2.0 source and GitHub main 5d5c04b63a0048af3e9245a06a41890777271034',assumptions:['Outputs below execute the supplied code with explicit fixed inputs.','Boss planner excludes optional d20 UI retry probability.','Game scores and balance weights are designer choices, not estimated learning effects.'],boss:B.create().backwardPlan(),bossBottomUp:B.create().strategy(),chicken:G.analyze(G.examples().chicken.matrix),sequentialChicken:G.solveTree(G.matrixTree(G.examples().chicken.matrix,['Yield','Charge'])),power:P.analyze([4,3,2,1],6),dean:M.apportion([1,2,3,4],12,'dean'),hill:M.apportion([1,2,3,4],12,'hill'),skill:M.skillCheck(10,2.4,3.4),vickrey:F.vickrey([100,80,30]),knaster:F.knaster([[100,40],[60,80]]),adjustedWinner:F.adjustedWinner([[60,40],[30,70]])};
const machine=VM.create(0);machine.clearance();machine.plan(7);machine.plan(15);model.missionMachine=machine.exportLog();
fs.writeFileSync(path.join(dest,'executed-math-log.json'),JSON.stringify(model,null,2)+'\n');
const inventory=[];function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','audit','node_modules'].includes(entry.name))continue;const p=path.join(dir,entry.name);if(entry.isDirectory())walk(p);else if(/\.(js|html|css|md|json|yml)$/.test(p)){const bytes=fs.readFileSync(p);inventory.push({path:path.relative(root,p),sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,functions:[...bytes.toString().matchAll(/function\s+([A-Za-z_$][\w$]*)\s*\(/g)].map(m=>m[1]),vendor:p.includes('/vendor/')});}}}walk(root);fs.writeFileSync(path.join(dest,'source-inventory.json'),JSON.stringify(inventory,null,2)+'\n');
console.log(JSON.stringify({bossValue:model.boss.value,bossActions:model.boss.actions,chickenMixed:model.chicken.interiorMixed,sequential:model.sequentialChicken.payoff,files:inventory.length}));
